### ISSUE TITLE
MPCDI didn't support to WIN32 program

### ISSUE THREAD

**Issue by namuhevil** [scaredyfish/MPCDI#1]
![Annotation 2021-06-01 155110](https://user-images.githubusercontent.com/24601573/120286805-39596980-c2f1-11eb-8f58-65f329b75d5a.png)

Why I can not use release mode or debug mode to run it? When I run it I encounter the problem with pictures. It said that mpcdi can not run under win32. But actually I use x64 to run. Which part I need to modify? 
I use visual studio 2019.

**Comment by scaredyfish** [comment]
This is not my code, so I can't really support it. I just put it on GitHub.

**Comment by namuhevil** [comment]
But had you ever tried this code? with running .exe files? Where I can ask about this questions?

**Comment by namuhevil** [comment]
Not only compiler
